name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  # This line removes the warning and opts into the new Node version
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drive2earn-files
          path: .
